services:
  metube:
    image: 'ghcr.io/alexta69/metube:latest'
    environment:
      - SERVICE_FQDN_METUBE
      - UID=1000
      - GID=1000
    volumes:
      - '/storage/jellyfin/yt:/downloads'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8081'
      interval: 2s
      timeout: 10s
      retries: 15
    labels:
      - traefik.http.routers.xg0cows-0-https.middlewares=auth

