services:
  gitea:
    image: 'gitea/gitea:latest'
    environment:
      - SERVICE_FQDN_GITEA_3000
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - '22222:22'
    volumes:
      - '/storage/coolify/gitea:/var/lib/gitea'
      - 'gitea-timezone:/etc/timezone:ro'
      - 'gitea-localtime:/etc/localtime:ro'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:3000'
      interval: 2s
      timeout: 10s
      retries: 15

